services:
  # web:
  #   depends_on:
  #     - postgres_db
  #   build: 
  #     context: ./web
  #     dockerfile: Dockerfile
  #   image: django-k8s:v1
  #   environment:
  #     - PORT=8020
  #   env_file:
  #     - web/.env
  #   ports:
  #     - "8001:8020"
  #   volumes:
  #     - ./web/.env:/app/.env
  #     - staticfiles:/app/staticfiles/
  #   command: >
  #     bash -c "chmod +x /app/migrate.sh && chmod +x /app/entrypoint.sh &&
  #             until pg_isready -h postgres_db -p 5432; do
  #               echo 'waiting for database...';
  #               sleep 2;
  #             done;
  #             /app/migrate.sh && /app/entrypoint.sh"

  postgres_db:
    image: postgres
    # command: ["postgres", "-p", "5433"]
    restart: always
    env_file:
      - web/.env
    expose:
      - 5432
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis_db:
    image: redis
    restart: always
    expose:
      - "6380"
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--port", "6380"]

volumes:
  # staticfiles:
  #     external: true
  postgres_data:
  redis_data:

