apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iac-python-deployment
  template:
    metadata:
      labels:
        app: iac-python-deployment
    spec:
      containers:
        - name: iac-python
          image: codingforentrepreneurs/iac-python:latest
          env:
            - name: PORT
              value: "8181"
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: iac-python-service
spec:
  selector:
    app: iac-python-deployment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8181
  type: LoadBalancer