name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test_django:
    uses: henryantwi/django-k8s-v2/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: not-so-secret
    steps:
    - uses: actions/checkout@v4
