name: Build Docker Container & Push to DigitalOcean Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test_django_job:
    uses: henryantwi/django-k8s-v2/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: not-so-secret
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Login to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200
    - name: Build Docker image
      working-directory: ./web
      run: |
        docker build -f Dockerfile \
          -t registry.digitalocean.com/nesttop-k8s/django-k8s-web:latest  \
          -t registry.digitalocean.com/nesttop-k8s/django-k8s-web:${GITHUB_SHA::7} \
          .
    - name: Push Docker image to DigitalOcean Container Registry
      run: |
        docker push registry.digitalocean.com/nesttop-k8s/django-k8s-web --all-tags