name: Rollout Django Deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rollout:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: not-so-secret
      CLUSTER_NAME: django-k8s
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: K8s Cluster kubeconfig file with / short-lived creds
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
    - name: Run rollout on deployment
      run: |
        kubectl rollout restart deployment/django-k8s-web-deployment